### ISSUE TITLE
simple-proxy

### ISSUE THREAD

**Issue by Link0Darck** [ericcwlaw/simple-proxy#1]
Hello,
Is there any way to have the ip of the person who connects to the server without being the ip of the proxy?
If not great the proxy system would miss more a version in udp and your proxy is complete

**Comment by ericcwlaw** [comment]
Thanks for your suggestion. It would be nice to forward the caller's IP address to the target socket.

However, node.js 'net' package does not support overriding the IP address in an outgoing TCP packet. To do this, low level socket library is required.

Currently audit trail of the caller's IP address is kept in the application log.
